config/routes.rb
AukingInformationDataSystem::Application.routes.draw do

  resources :registration_confirmations, :only => [:new, :edit]
  resources :password_resets
  
  resources :users, :shallow => true do
    resources :guidances
  end  

  match 'tweets', :to => 'tweets#inbox'
  match 'tweets/new', :to => 'tweets#new'
  match 'tweets/create', :to => 'tweets#create'
  resources :users do
    resources :tweets
  end
  
  post "versions/:id/revert" => 'versions#revert', :as => 'revert_version'
  
  
  match '/guidances', :to => 'guidances#all'

  resources :sessions
  
  match '/grows', :to => 'grows#index'
  resources :farmers, :shallow => true do
    resources :grows
  end
  
  resources :crops
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  
  root :to => "home#index"
  
  resources :pesticides
  
  resources :images
  match 'images/upload', :to => 'images#upload'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected :user_id
  
  # tell rails to use its default password encryption
  has_secure_password
  
  validates :username, :presence => true,
                       :uniqueness => { :case_sensitive => false } 
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                   
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  validates :name, :presence => true
                                       
  # I guess, everyone should have a mobile before you register as a pro                
  validates :mobile, :presence => true
  
  validates :password, :presence => true,
                       :length => { :within => 4..40 },
                       :confirmation => false
  
  # user have many guidances, if user is destroyed(the technician is dismissed), the guidances will be destroyed
  has_many :guidances, :dependent => :destroy
  # since guidances table is just a joint for user and farmer, therefore, we still need
  # to specify user can support multiple farmers at the sametime
  has_many :farmers, :through => :guidances
  
  has_many :user_emails
  has_many :user_addresses
  has_many :user_telecoms
  
  # privilliage
  has_many :assignments, :dependent => :destroy
  has_many :roles, :through => :assignments
  
  # can upload multiple images
  has_many :images
  
  # allows to upload a picture as the user's profile avatar through form.
  # In the database, there is a column is called avatar
  mount_uploader :avatar, AvatarUploader
  
  def support!(farmer, note=nil)
    guidances.create!(:farmer_id => farmer.id, :note => note)
  end
  
  # this generate a unique random token
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def send_registration_confirmation
    generate_token(:activation_token)
    # Although we only update the activation token, the validation will be processed by default
    # in order to save it correctly, we have to ignore validation
    save! :validate => false    
    UserMailer.registration_confirmation(self).deliver
  end
  
  # generate token and send out the email
  def send_password_reset
    generate_token(:password_reset_token)
    # Although we only update the reset token, the validation will be processed by default
    # in order to save it correctly, we have to ignore validation
    save! :validate => false
    UserMailer.password_reset(self).deliver
  end
  
  def activated?
    return self.activation_token.nil?
  end
  
  def activate
    # nil the token, indicate this account is activated
    self.activation_token = nil # why we have to use "self" ???
    
    save! :validate => false
  end
  
  def deactivate
    
  end
  
  # check if user is such role
  def has_role?(role_sym)
    # scan through all elements in roles array
    # if the conditional statment in the block ever return true,
    # the whole process will be true
    roles.any? do |role|
      role.name.underscore.to_sym == role_sym
    end
  end
  
  def assign!(role_sym)
    role = Role.where(:name => role_sym)[0]
    assignments.create!(:role_id => role.id) if role
  end
  
  def role=(role)
    assignments.create!(:role_id => role.id) if role
  end
  
  # pass :all to resign user completely
  def resign(role_sym)
    if role_syms == :all
      assignments.delete_all
    else
      role = Role.where(:name => role_sym)[0]
      assignment = assignments.find(role.id)[0]
      assignment.destroy if assignment
    end
  end
  
  
  # ====================================== microblog related methods
  def redis_key(type)
    return %(user:#{self.id}:#{type})
  end
  
  def follow!(user)
    REDIS.multi do
      # this current user is now following the target user
      REDIS.sadd(self.redis_key(:following), user.id)
      # this current user is now, a follower of the target user
      REDIS.sadd(user.redis_key(:followers), self.id)
    end
  end
  
  # For testing only
  def friend!(user)
    self.follow!(user)
    user.follow!(self)
  end
  
  def unfollow!(user)
    REDIS.multi do
      # this current user is no longer following the target user
      REDIS.srem(self.redis_key(:following), user.id)
      # this current user is no longer a follower of the target user
      REDIS.srem(user.redis_key(:followers), self.id)
    end
  end
  
  def followers
    follower_ids = REDIS.smembers(self.redis_key(:followers))
    return User.where(:id => follower_ids)
  end
  
  def following
    following_ids = REDIS.smembers(self.redis_key(:following))
    return User.where(:id => following_ids)
  end
  
  def friends
    # intersection of followers and following sets, will be the friends set.
    # friend has mutual relationship(you follows him, he also follows you)
    # note that, the params are two key names
    friend_ids = REDIS.sinter(
      self.redis_key(:followers), 
      self.redis_key(:following)
    )
    return User.where(:id => friend_ids)
  end
  
  def followed_by?(user)
    REDIS.sismember(redis_key(:followers), user.id)
  end
  
  def following?(user)
    REDIS.sismember(redis_key(:following), user.id)
  end
  
  def followers_count
    REDIS.scard(redis_key(:followers))
  end
  
  def following_count
    REDIS.scard(redis_key(:following))
  end
  
  # TODO: implement attachment
  def tweet(content)
    # convert the current time into integer as a score for personal timeline
    time_now = Time.now
    time_score = time_now.to_i
    
    tweet_id = REDIS.incr('tweet:next_id')
    core_id = REDIS.incr('core:next_id')
    
    REDIS.hmset( %(tweet:#{tweet_id}), 
      :id, tweet_id,
      :core_id, core_id,
      :pub_date, time_now )
      
    REDIS.hmset( %(core:#{core_id}),
      :id, core_id,
      :author, self.id,
      :content, content,
      :create_date, time_now )
    
    
    # push tweet to the global timeline
    # for displaying in the website's front page or something else... or monitoring
    # put the tweet into global tweets timeline
    REDIS.lpush( %(global:timeline), tweet_id )
    
    # for displaying the user's tweet on his home page
    # put the tweet into the current user's tweet timeline, this timeline contains only his own tweets and retweet
    REDIS.zadd( self.redis_key(:timeline), time_score, tweet_id )
    
    # put the tweet into the user's own inbox list
    REDIS.lpush( self.redis_key(:inbox), tweet_id )
    
    # put the tweet into the followers inbox list
    self.followers.each do |follower|
      REDIS.lpush( follower.redis_key(:inbox), tweet_id )
    end
    
    # TODO: implement mentions, notify them been mentioned
    
    return tweet_id
  end
  
  def reply(target_id, content, is_public)
    time_now = Time.now
    time_score = time_now.to_i
        
    reply_id = REDIS.incr('tweet:next_id')
    reply_core_id = REDIS.incr('core:next_id')
    
    REDIS.hmset( %(tweet:#{reply_id}), 
      :id, reply_id,
      :core_id, reply_core_id,
      :pub_date, time_now )
      
    REDIS.hmset( %(core:#{reply_core_id}),
      :id, reply_core_id,
      :author, self.id,
      :content, content,
      :create_date, time_now )
    
    # put reply to the user's timeline sorted set
    REDIS.zadd( %(user:#{self.id}:timeline), time_score, reply_id )
    # push reply to the user's inbox list
    REDIS.lpush( self.redis_key(:inbox), reply_id )
    
    
    # OVERVIEW of what should happen next:
    # the reply will be added to the reply target's replies list.
    # And if the reply target is not the root of conversation.(the tweet started
    # the conversation) Then the reply tweet_id will need to be added to the 
    # root tweet's replies list as well
    # 
    #
    #   replies       target replies
    #   ----------------------------------------------------------------------- left push 
    #   tweet:2       REPLY:7
    #   tweet:3       tweet:5     
    #   TARGET:4       
    #   tweet:5                                               ROOT:1
    #   tweet:6                           ROOT:1              tweet:2
    #   REPLY:7                           tweet:2             TARGET:4            
    #   ----------------------------------------------------------------------- right push
    #                                     target parents      reply parents
    #
    #
    
    # Push the reply tweet to the core of reply target's replies list
    target_core_id = REDIS.hget( %(tweet:#{target_id}), :core_id )
    REDIS.lpush( %(core:#{target_core_id}:replies), reply_id )
    
    
    # check if the target tweet's parents list exist, if it does not,
    # it means the target tweet is the root tweet no need to add the new tweet
    # to its replies list. if it DOES exist, then the target tweet is a children
    # of the FIRST element(root) of the target tweet's parents list, and you need to 
    # push the new tweet into the root's replies list
    target_parents_key = %(core:#{target_core_id}:parents)
    
    # Replying to the root tweet?
    
    # target tweet's parents list exists(not 0), you are REPLYING A REPLY of the root tweet
    # you need to add the reply to the root's replies as well
    is_replying_root = REDIS.llen(target_parents_key) == 0
    # replying a reply
    if( !is_replying_root ) 
      # get the all the target parent tweets's id
      target_parent_ids = REDIS.lrange( target_parents_key, 0, -1 )
      # root tweet id is the first one
      root_id = target_parent_ids[0]
      
      # add the reply id to the root tweet's replies list
      root_core_id = REDIS.hget( %(tweet:#{root_id}), :core_id )
      REDIS.rpush( %(core:#{root_core_id}:replies), reply_id )
      
      # update the reply target's parents list, the new list will include the reply target's tweet id
      REDIS.rpush( %(core:#{reply_core_id}:parents), target_parent_ids.push(target_id))

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # use greet layout on user signup
  layout 'greet', :only => [:new, :create]
  
  # this method will detect the restful style of request, load and authorize the
  # resrouce, so you don't need to query to the data anymore, it is already loaded.
  # load_and_authorize_resource
  
  skip_authorization_check :only => [:new, :create]
  
  
  def index
    authorize! :index, User
    
    @users = User.all
  end
  
  def show
    @user = User.find_by_id(params[:id])
    
    authorize! :index, @user
    
    render :layout => 'application_full'
  end

  def new
    # if user is in local network, they can register a new user
    if !in_local_network?
      flash[:error] = 'You are not in the local network, cannot create a new user!'
      redirect_to root_path
      return
    end
    
    @user = User.new
  end

  def create
    # if user is in local network, they can register a new user
    if !in_local_network?
      flash[:error] = 'You are not in the local network, cannot create a new user!'
      redirect_to root_path
      return
    end
    
    @user = User.new(params[:user])
    if @user.save
      # send out the activation email to the user
      @user.send_registration_confirmation
      # route user to the confirmation email sent page
      flash[:info] = "An confirmation email has sent to your mailbox"
      redirect_to new_registration_confirmation_path
    else
      flash[:error] = @user.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<table class="table table-bordered table-striped sortable-table">
	<thead>
		<tr>
			<th class="header">ID</th>
			<th class="header">姓名</th>
			<th class="header">权限</th>
            <th class="header">邮箱</th>
            <th class="header">电话</th>
			<th class="header">指导农户</th>
		</tr>
	</thead>
	
	<tbody>
		<% @users.each do |user| %>
			<tr>
			<td><%= user.id %></td>
			<td><%= link_to user.name, user_path(user) %></td>
			<td><%= user.roles.map { |r| r.name }.join(", ") %></td>
			<td><%= user.email %></td>
			<td><%= user.mobile %></td>
			<td><%= user.farmers.count %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<!-- 
If you want to upload an image, the html form encoding must be set to multipart/form-data, that is done by set ':multipart => true' 

:validate => true is for client_side_validation gem, doing validation dynamically

-->
<%= form_for @user, :validate => true, :html => {:multipart => true, :class => "form-horizontal"} do |f| %>
	<div class="control-group">
		<%= label_tag :username, t(:username), :class => "control-label" %>
		<div class="controls"><%= f.text_field :username, :placeholder => t(:username) %></div>
	</div>
	<div class="control-group">
		<%= label_tag :email, t(:email), :class => "control-label" %>
		<div class="controls"><%= f.text_field :email, :placeholder => t(:email) %></div>
	</div>
	<div class="control-group">
		<%= label_tag :password, t(:password), :class => "control-label" %>
		<!-- note that we have to explicit set validate confirmation to false, otherwise client_side_validations gem will always try to confirm password -->
		<div class="controls"><%= f.password_field :password, :placeholder => t(:password), :validate => {:confirmation => false} %></div>
	</div>
	<div class="control-group">
		<%= label_tag :name, t(:full_name), :class => "control-label" %>
		<div class="controls"><%= f.text_field :name, :placeholder => t(:full_name) %></div>
	</div>
	<div class="control-group">
		<%= label_tag :mobile, t(:mobile), :class => "control-label" %>
		<div class="controls"><%= f.text_field :mobile, :placeholder => t(:mobile) %></div>
	</div>
	<div class="control-group">
		<%= label_tag :avatar, t(:avatar), :class => "control-label" %>
		<div class="controls"><%= f.file_field :avatar %></div>
	</div>
	<div class="form-actions">
		<%= f.submit t(:signup), :class => 'btn btn-success'%>
	</div>
<% end %>

app/views/users/show.html.erb
<div class="row-fluid farmer-card">
	<div class="span9">
		<h3><%= link_to @user.name, user_path(@user.id) %></h3>
		
		<p>
			<%= @user.email%>
		</p>
		<p>
			<%= @user.mobile%>
		</p>		
	</div>
	
	<div class="span3 farmer">
		<div class="thumbnail">
			<div class="caption">
				<a class="small-grid" href="<%= user_path(@user.id) %>">
					<% if @user.avatar? %>
						<%= image_tag @user.avatar_url(:thumb) %>
					<% else %>
						<img class="thumbnail" src="http://placekitten.com/g/90/90">
					<% end %>
				</a>
				<h5>Thumbnail label</h5>
              	<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              	<p>
					<%= link_to "负责农户", new_user_guidance_path(@user), {:class => "btn btn-primary"}%>
					<a href="#" class="btn">个人资料</a>
				</p>
			</div>
		</div>
	</div>
	
</div>

<br/>

<table class="table table-bordered table-striped sortable-table">
	<thead>
		<tr>
			<th class="header">ID</th>
			<th class="header">姓名</th>
            <th class="yellow header headerSortDown">耕地面积</th>
            <th class="blue header">种植面积</th>
			<th class="header">电话</th>
			<th class="header">城市</th>
			<th class="header">作物数量</th>
		</tr>
	</thead>
	
	<tbody>
		<% @user.guidances.each do |guidance| %>
			<tr>
			<td><%= guidance.farmer.id %></td>
			<td><%= link_to guidance.farmer.name, farmer_path(guidance.farmer) %></td>
			<td><%= guidance.farmer.arable %></td>
			<td><%= guidance.farmer.cultivated %></td>
			<td><%= 
				if guidance.farmer.telecoms.count != 0 
					guidance.farmer.telecoms[0].value
				end
			%></td>
			<td><%=
				if guidance.farmer.addresses.count != 0 
					guidance.farmer.addresses[0].city
				end
			 %></td>
			<%
			  	crops = []
				guidance.farmer.grows.each do |grow|
					crops.push(grow.crop.category)
				end
			%>
			<td><%= truncate(crops.join("，"), :length => 15) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>