config/routes.rb
AukingInformationDataSystem::Application.routes.draw do

  resources :registration_confirmations, :only => [:new, :edit]
  resources :password_resets
  
  resources :users, :shallow => true do
    resources :guidances
  end  

  match 'tweets', :to => 'tweets#inbox'
  match 'tweets/new', :to => 'tweets#new'
  match 'tweets/create', :to => 'tweets#create'
  resources :users do
    resources :tweets
  end
  
  post "versions/:id/revert" => 'versions#revert', :as => 'revert_version'
  
  
  match '/guidances', :to => 'guidances#all'

  resources :sessions
  
  match '/grows', :to => 'grows#index'
  resources :farmers, :shallow => true do
    resources :grows
  end
  
  resources :crops
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  
  root :to => "home#index"
  
  resources :pesticides
  
  resources :images
  match 'images/upload', :to => 'images#upload'

end

app/models/grow.rb
class Grow < ActiveRecord::Base
  attr_protected :farmer_id
  
  belongs_to :farmer
  
  belongs_to :crop
  has_one :harvest_info
  
  has_many :fertilizer_applications, :dependent => :destroy
  has_many :fertilizers, :through => :fertilizer_applications
  
  has_many :pesticide_applications, :dependent => :destroy
  has_many :pesticides, :through => :pesticide_applications
  
  has_many :sufferings, :dependent => :destroy
  has_many :harms, :through => :sufferings
  
  # allow elastic search to search record, add index
  include Tire::Model::Search
  # update the index when model is updated
  # include Tire::Model::Callbacks
  # TODO: remove this on production mode
  after_save do
    # db:populate rake task will set the seed a certain value, in order 
    # to save time during seeding process. In the 
    self.update_index if ENV["seed"].nil?
  end
  after_destroy do
    self.update_index
  end
  
  mapping do
    indexes :id, type: 'string', index: 'not_analyzed', include_in_all: false
    indexes :sown_area, type: 'float'
    indexes :sowing_date, type: 'date'
  end
  
  def to_indexed_json
    {
      farmer: self.farmer.name,
      crop: {
        id: self.crop_id,
        category: self.crop.category
      },
      sown_area: self.sown_area,
      sowing_date: self.sowing_date,
      crop_id: self.crop_id,
      harm_ids: self.harm_ids,
      pesticide_ids: self.pesticide_ids,
    }.to_json
  end
  
  def self.search(params)
    # page specify the start page, per_page specify how many items per page
    tire.search(load: true, page: params[:page], per_page: 20) do 
      query { 
        string params[:query], default_operator: 'AND'
      } if params[:query].present?
      
      # define image tags facet
      facet 'crop_tags' do
        # by default only 10 facets will be created, therefore, make sense to set it to the 
        # total number of the entries in the database
        terms(:crop_id, :size => Crop.all.count)
      end
      
      # filter the search result depends on the selected facet(s)
      filter :term, crop_id: params[:crop_id] if params[:crop_id].present?
      
      
      # pesticide tags facets
      facet 'pesticide_tags' do
        # by default only 10 facets will be created, therefore, make sense to set it to the 
        # total number of the entries in the database
        terms(:pesticide_ids, :size => Pesticide.all.count)
      end
      
      # filter the search result depends on the selected facet(s)
      filter :term, pesticide_ids: params[:pesticide_ids] if params[:pesticide_ids].present?
      
      # pesticide tags facets
      facet 'harm_tags' do
        # by default only 10 facets will be created, therefore, make sense to set it to the 
        # total number of the entries in the database
        terms(:harm_ids, :size => Harm.all.count)
      end
      
      # filter the search result depends on the selected facet(s)
      filter :term, harm_ids: params[:harm_ids] if params[:harm_ids].present?      
      
    end
  end
  
  def suffer!(harm)
    sufferings.create!(:harm_id => harm.id)
  end
  
  def fertilize!(fertilizer, amount, date)
    fertilizer_applications.create!(:fertilizer_id => fertilizer.id, :amount => amount, :date => date)
  end
  
  def use_pesticide!(pesticide, amount, date)
    pesticide_applications.create!(:pesticide_id => pesticide.id, :amount => amount, :date => date)
  end
end

app/controllers/grows_controller.rb
class GrowsController < ApplicationController
  load_and_authorize_resource
  
  # list the grows belongs to a specific farmer
  def index
     @grows = Grow.search(params)
  end
  
  # show the specific grow of a specific farmer
  def show
    @grow = Grow.find(params[:id])
  end
  
  # add a new grow to the farmer
  def new
    @farmer = Farmer.find_by_id(params[:farmer_id])
    @grow = @farmer.grows.build
    @crops = Crop.all
  end

  def create
    @farmer = Farmer.find_by_id(params[:farmer_id])
    @grow = @farmer.grows.build(params[:grow])
    if @grow.save
      flash[:success] = 'Successfully created the grow!'
      redirect_to farmer_path(@farmer)
    else
      render 'new', :flash => {:error => @grow.errors.full_messages}
    end
  end

  def edit

  end

  def update
    if @grow.update_attributes(params[:grow])
      flash[:success] = 'Successfully updated the grow!'
      redirect_to grow_path(@grow)
    else
      flash[:success] = 'Update failed!'
      render 'edit'
    end
  end

  def destroy
  end

end

app/helpers/grows_helper.rb
module GrowsHelper
end

app/views/grows/edit.html.erb
<!-- TODO: need nested form for pesticide application, fertilizer application, and harm suffered -->
<%= simple_form_for @grow do |f| %>
	<%= f.association :pesticides, :include_blank => true %>
	<%= f.association :fertilizers, :include_blank => true %>
	<%= f.association :harms, :include_blank => true %>
	<%= f.input :sowing_date, :as => :date, :start_year => Date.today.year - 10, :end_year => Date.today.year, :default => Date.today %>
	<%= f.button :submit, :class => 'btn-warning' %>
<% end %>

app/views/grows/index.html.erb
<% content_for :aside do %>
<div class="span2">
	<div class="well sidebar-nav">
	<%= form_tag grows_path, :class => 'form-search', method: :get do %>
		<%= text_field_tag :query, params[:query], :class => 'input-medium search-query', :placeholder => t('search') %>
	<% end %>
	
	<ul class="nav nav-list">
		<li class="nav-header"><%= Crop.model_name.human %></li>
		<% @grows.facets['crop_tags']['terms'].each do |facet| %>
		<li>
			<span class="label label-info"><%= link_to_unless_current Crop.find(facet['term']).category, params.merge(crop_id: facet['term']) %></span>
			<% if params[:crop_id] == facet['term'].to_s %>
				<span class="pull-right"><%= link_to 'remove', crop_id: nil %></span>
			<% else %>
				<span class="pull-right"><%= facet['count'] %></span>
			<% end %>
		</li>
		<% end %>
	</ul>
	
	<ul class="nav nav-list">
		<li class="nav-header"><%= Pesticide.model_name.human %></li>
		<% @grows.facets['pesticide_tags']['terms'].each do |facet| %>
		<li>
			<span class="label label-info"><%= link_to_unless_current Pesticide.find(facet['term']).name, params.merge(pesticide_ids: facet['term']) %></span>
			<% if params[:pesticide_ids] == facet['term'].to_s %>
				<span class="pull-right"><%= link_to 'remove', pesticide_ids: nil %></span>
			<% else %>
				<span class="pull-right"><%= facet['count'] %></span>
			<% end %>
		</li>
		<% end %>
	</ul>
	
	<ul class="nav nav-list">
		<li class="nav-header"><%= Harm.model_name.human %></li>
		<% @grows.facets['harm_tags']['terms'].each do |facet| %>
		<li>
			<span class="label label-info"><%= link_to_unless_current Harm.find(facet['term']).name, params.merge(harm_ids: facet['term']) %></span>
			<% if params[:harm_ids] == facet['term'].to_s %>
				<span class="pull-right"><%= link_to 'remove', harm_ids: nil %></span>
			<% else %>
				<span class="pull-right"><%= facet['count'] %></span>
			<% end %>
		</li>
		<% end %>
	</ul>
	
	</div>
</div>
<% end %>

<%= bootstrap_will_paginate @grows %>

<!-- grows table, shared by farmer and grow view -->
<table class="table table-bordered table-striped sortable-table">
	<thead class="table-header">
		<tr>
			<th class="header">ID</th>
			<th class="header blue"><%= Farmer.model_name.human %></th>
			<th class="header">作物种类</th>
            <th class="yellow header headerSortDown">播种面积</th>
            <th class="blue header">播种时间</th>
            <th class="blue header"><%= Harm.model_name.human %></th>
            <th class="blue header"><%= Pesticide.model_name.human %></th>
		</tr>
	</thead>
	
	<tbody>
		<% @grows.each do |g| %>
			<tr>
				<td>
					<a href="<%= grow_path(g) %>"><i class='icon-cog'></i><%= g.id %></a>
				</td>
				<td><%= link_to g.farmer.name, farmer_path(g.farmer) %></td>
	            <td><%= 
					link_to g.crop.category, crop_path(g.crop), {
						:class => 'crop-popover-trigger',
						'data-original-title' => "<span class='label success'>#{g.crop.quality}</span>",
						'data-content' => "<img src='#{g.crop.image}' width='100' height='100'/><h5>生育期</h5>#{g.crop.growth_start}<br/>#{g.crop.growth_end}"
						} 
					%>
				</td>
	            <td><%= g.sown_area %></td>
	            <td><%= g.sowing_date %></td>
				<td><%= truncate(g.harms.map{|h| h.name}.join(','), :length => 10)%></td>
				<td><%= truncate(g.pesticides.map{|p| p.name}.join(','), :length => 10)%></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/grows/new.html.erb
<%= form_for [@farmer, @grow] do |f| %>
	<h3>添加作物种植信息</h3>
	<p>
		<%= collection_select(:grow, :crop_id, @crops, :id, :category) %>
	</p>
	<p>
		<%= f.text_field :sown_area, :placeholder => "播种面积" %>
	</p>
	<p>
		<%= date_select("grow", "sowing_date") %>
	</p>
	
	<p><%= f.submit '添加', :class => 'btn success' %></p>
<% end %>

app/views/grows/show.html.erb
<h2><%= @grow.crop.category %></h2>

<ul class="nav nav-tabs">
	<li class="active"><a data-target="#pesticide" data-toggle="tab">施药水平</a></li>
	<li><a data-target="#fertilizer" data-toggle="tab">施肥水平</a></li>
	<li><a data-target="#harms" data-toggle="tab">病虫草害</a></li>
</ul>

<div class="tab-content">
	
  	<div class="tab-pane active fade in" id="pesticide">
		<table class="table table-bordered table-striped sortable-table">
			<thead>
				<tr>
					<th class="header">名字</th>
					<th class="header">种类</th>
		            <th class="yellow header headerSortDown">时间</th>
		            <th class="blue header">施药量</th>
				</tr>
			</thead>
			<tbody>
				<% @grow.pesticide_applications.each do |pa|  %>
				<tr>
					<td><%= pa.pesticide.name%></td>
		            <td><%= pa.pesticide.category %></td>
		            <td><%= pa.date %></td>
		            <td><%= pa.amount %></td>
				</tr>
				<% end %>	
			</tbody>
		</table>
  	</div>

	<div class="tab-pane fade" id="fertilizer">
		<table class="table table-bordered table-striped sortable-table">
			<thead>
				<tr>
					<th class="header">名称</th>
					<th class="header">类型</th>
					<th class="header">公斤／亩</th>
					<th class="header">施用日期</th>
					<th class="header">N</th>
		            <th class="yellow header headerSortDown">P</th>
		            <th class="blue header">K</th>
		            <th class="blue header">其他</th>
				</tr>
			</thead>
			<tbody>
				<% @grow.fertilizer_applications.each do |fa| %>
				<tr>
					<td><%= fa.fertilizer.name %></td>
					<td><%= fa.fertilizer.category %></td>
		            <td><%= fa.amount %></td>
					<td><%= fa.date %></td>
		            <td><%= fa.fertilizer.n %></td>
		            <td><%= fa.fertilizer.p %></td>
		            <td><%= fa.fertilizer.k %></td>
		            <td><%= fa.fertilizer.others %></td>
				</tr>
				<% end %>		
			</tbody>
		</table>
  	</div>

  	<div class="tab-pane fade" id="harms">
		<table class="table table-bordered table-striped sortable-table">
			<thead>
				<tr>
					<th class="header">病害类型</th>
				</tr>
			</thead>
			<tbody>	
				<% @grow.harms.each do |h|  %>
				<tr>
					<td><%= h.name %></td>
				</tr>
				<% end %>	
			</tbody>
		</table>
  	</div>
</div>

<%= link_to t('helpers.submit.edit', :model => Grow.model_name.human), edit_grow_path(@grow), :class => 'btn btn-warning'%>
<%= link_to t('helpers.submit.delete', :model => Grow.model_name.human), @grow, :method => :delete, :class => 'btn btn-danger'%>