config/routes.rb
AukingInformationDataSystem::Application.routes.draw do

  resources :registration_confirmations, :only => [:new, :edit]
  resources :password_resets
  
  resources :users, :shallow => true do
    resources :guidances
  end  

  match 'tweets', :to => 'tweets#inbox'
  match 'tweets/new', :to => 'tweets#new'
  match 'tweets/create', :to => 'tweets#create'
  resources :users do
    resources :tweets
  end
  
  post "versions/:id/revert" => 'versions#revert', :as => 'revert_version'
  
  
  match '/guidances', :to => 'guidances#all'

  resources :sessions
  
  match '/grows', :to => 'grows#index'
  resources :farmers, :shallow => true do
    resources :grows
  end
  
  resources :crops
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  
  root :to => "home#index"
  
  resources :pesticides
  
  resources :images
  match 'images/upload', :to => 'images#upload'

end

app/controllers/home_controller.rb
#coding: utf-8
class HomeController < ApplicationController
  skip_authorization_check
  
  def index
    # get the rss information
    require 'simple-rss'
    require 'open-uri' 
    require 'iconv'
    
    # force to read rss as UTF-8
    i = Iconv.new('UTF-8', 'UTF-8')
    # Seems like there is a bug on bitbucket's rss feed. If you try to open the feed it will auto detect the 
    # encoding as western ISO-8859-1, but it is actually is in UTF-8 encoding
    @rss = SimpleRSS.parse i.iconv(open('https://bitbucket.org/Liy/farmland/rss?token=d6396f0515485dc58a8de43fe7328bc2').read)
    
    if current_user.nil?
      flash.now[:info] = "超级帐户：li_yang</br>领班用户名：liu_sisi<br/>普通员工用户名：zeng_ziyi<br/>密码：0000"
    	render 'signin', :layout => 'greet'
    else
      # for now redirect to current user information page.
      # redirect_to current_user
      redirect_to tweets_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  #http://stackoverflow.com/questions/195740/how-do-you-do-relative-time-in-rails
  def pretty_date(dateTime)
    a = (Time.now - dateTime).to_i
    
    # second  1
    # minute  60
    # hour    3600
    # day     86400
    # week    604800
    # month   2419200
    # year    29030400
    
    case a
      when 0...60 then return t 'past.just_now'
      when 60...3600 then return t 'past.x_minutes_ago', :count => (a/60).to_i
      when 3600...86400 then return t 'past.x_hours_ago', :count => (a/3600).to_i 
      when 86400...604800 then return t 'past.x_days_ago', :count => (a/(3600*24)).to_i
      when 604800...2419200 then return t 'past.x_weeks_ago', :count => (a/(7*3600*24)).to_i
      when 2419200...29030400 then return t 'past.x_months_ago', :count => (a/(4*7*3600*24)).to_i
    end
    return t 'past.x_years_ago', :count => ((a)/(12*4*7*3600*24)).to_i
  end
end

app/views/home/_recent_commits.html.erb
<h2><%= t 'recent_update' %></h2>
<hr>
<div><% tracked = nil %>
<% @rss.items.each do |item| %>
	<% prettyPubDate = pretty_date(item.pubDate.to_time) %>
	<% if tracked != prettyPubDate %>
		<% tracked = prettyPubDate %>
		<span class="label label-info"><%= prettyPubDate %></span>
	<% end %>
	
	<pre><%= raw item.title %></pre>
<% end %>
</div>

app/views/home/desktop.html.erb
<% content_for :aside do %>
<!-- testing facet -->
<div class="span2">
	<div class="well sidebar-nav">
		
		<ul class="nav nav-list">
			<li class="nav-header"><%= t('task_list') %></li>

		</ul>
		
	</div>
</div>
<% end %>

<h1><%= User.model_name.human %>: <%= current_user.name %></h1>
<p><%= link_to '发消息', '#', :class => "btn btn-primary"%></p>
<%= render 'recent_commits' %>

app/views/home/signin.html.erb
<div class="hero-unit">
<%= form_tag sessions_path, :class => "form-horizontal" do %>
	<div class="control-group">
		<%= label_tag :username, t(:username), :class => "control-label" %>
		<div class="controls">
			<%= text_field_tag :username, params[:username], :placeholder => t(:username) %>
		</div>
	</div>
	
	<div class="control-group">
		<%= label_tag :password, t(:password), :class => "control-label" %>
		<div class="controls">
			<input id="password" name="password" type="password" placeholder="<%= t(:password) %>">
		</div>
	</div>
	<div class="form-actions">
		<%= submit_tag t(:signin), :class => 'btn btn-primary'%>
		<%= link_to t(:forgot_password), new_password_reset_path, :id => "forgot-passowrd" %>
	</div>
<% end %>
</div>
<%= render 'recent_commits' %>