config/routes.rb
AukingInformationDataSystem::Application.routes.draw do

  resources :registration_confirmations, :only => [:new, :edit]
  resources :password_resets
  
  resources :users, :shallow => true do
    resources :guidances
  end  

  match 'tweets', :to => 'tweets#inbox'
  match 'tweets/new', :to => 'tweets#new'
  match 'tweets/create', :to => 'tweets#create'
  resources :users do
    resources :tweets
  end
  
  post "versions/:id/revert" => 'versions#revert', :as => 'revert_version'
  
  
  match '/guidances', :to => 'guidances#all'

  resources :sessions
  
  match '/grows', :to => 'grows#index'
  resources :farmers, :shallow => true do
    resources :grows
  end
  
  resources :crops
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  
  root :to => "home#index"
  
  resources :pesticides
  
  resources :images
  match 'images/upload', :to => 'images#upload'

end

app/controllers/application_controller.rb
#coding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # ensure every action is authorized, lock it down
  check_authorization
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :flash => {:error => t('flash.unauthorized')}
  end
  
  before_filter :setup_locale
  
  def setup_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def site_name
    return t(:title)
  end
  helper_method :site_name
  
  def company_name
    return t(:company)
  end
  helper_method :company_name
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  # expose this method to other controllers
  helper_method :current_user
  
  
  
  # check to see if the request is from a local network range...
  def in_local_network?
    # TODO: check a certain range of ip address 
    # require 'ipaddr'
    #     ip_i = IPAddr.new(request.remote_ip).to_i
    #     return ip_i == IPAddr.new('127.0.0.1').to_i
    return true
  end
  helper_method :in_local_network?
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, btnType, f)
    # this returns two strings, one is a hidden field and another is a link to the remove
    # field function
    return f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)", :class => "btn " + btnType)
  end
  
  # association should be a symbol
  def link_to_add_fields(name, f, association)
    # create corresponding ruby instance of the association so the field can reference to, e.g, if it is a address, then
    # FarmerEmail ruby object will be created.
    new_object = f.object.class.reflect_on_association(association).klass.new
    
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    
    link_to_function(name, "add_fields(this, '#{association}', '#{escape_javascript(fields)}')", :class => "btn btn-info btn-small")
  end
  
  def link_to_google_map (addr)
    	s = Geocoder.search( addr ) 
  		lat = s[0].latitude
  		lng = s[0].longitude
  end
  
  # bootstrap style of pagination
  # Based on https://gist.github.com/1205828, in turn based on https://gist.github.com/1182136
  class BootstrapLinkRenderer < ::WillPaginate::ActionView::LinkRenderer
    protected

    def html_container(html)
      tag :div, tag(:ul, html), container_attributes
    end

    def page_number(page)
      tag :li, link(page, page, :rel => rel_value(page)), :class => ('active' if page == current_page)
    end

    def gap
      tag :li, link(super, '#'), :class => 'disabled'
    end

    def previous_or_next_page(page, text, classname)
      tag :li, link(text, page || '#'), :class => [classname[0..3], classname, ('disabled' unless page)].join(' ')
    end
  end

  def bootstrap_will_paginate(pages)
    will_paginate(pages, :class => 'pagination', :inner_window => 2, :outer_window => 0, :renderer => BootstrapLinkRenderer, :previous_label => '&larr;'.html_safe, :next_label => '&rarr;'.html_safe)
  end
  

  
end

app/views/application/_flash_prompt.html.erb
<% flash.each do |key, value| %>
	<% if !value.nil? %>
		<div class="alert alert-<%= key %>">
			<a class="close" href="#" data-dismiss="alert">×</a>
			<!-- be careful with the row method! -->
			<%= raw(value) %>
		</div>
	<% end %>
<% end %>

app/views/application/_footer.html.erb
<hr>
<footer id="footer">
  <p>&copy; <%= company_name %> 2011</p>

<!-- debug message -->
<% if Rails.env.development? %>
	<%= debug(params) %>
<% end %>
<span class="label label-info"><%= request.env['SERVER_SOFTWARE'] %></span> <span class="label label-info"><%= request.remote_ip %></span> <span class="label"><%= request.user_agent %></span>

</footer>

app/views/application/_header.html.erb
<title><%= site_name %></title>
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/application/_top_menu.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container" style="width: auto;">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
	          	<span class="icon-bar"></span>
	          	<span class="icon-bar"></span>
	        </a>
			<a class="brand" href="<%= root_path %>" style="margin-left:0px"><%= site_name %></a>
			<div class='nav-collapse'>			
				<ul class="nav">
					<li><%= link_to User.model_name.human, users_path %></li>
					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= Farmer.model_name.human %><b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to t('menu.action.browse'), farmers_path %></li>
							<li class="divider"></li>
							<li><%= link_to t('menu.action.add'), new_farmer_path %></li>
						</ul>
					</li>
			
					<li><%= link_to Grow.model_name.human, grows_path %></li>
					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= Pesticide.model_name.human %>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to t('menu.action.browse'), pesticides_path %></li>
							<li class="divider"></li>
							<li><%= link_to t('menu.action.add'), new_pesticide_path %></li>
						</ul>
					</li>
			
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= Crop.model_name.human %>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to t('menu.action.browse'), crops_path %></li>
							<li class="divider"></li>
							<li><%= link_to t('menu.action.add'), new_crop_path %></li>
						</ul>
					</li>
					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= Image.model_name.human %>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to t('menu.action.browse'), images_path %></li>
							<li class="divider"></li>
							<li><%= link_to t('menu.action.add'), new_image_path %></li>
						</ul>
					</li>
				</ul>
				
				<ul class="nav pull-right">
					<li>
						<% if current_user.nil? %>
						<%= link_to t(:signin), signin_path %>
						<% else %>
						<%= link_to t(:signout), signout_path, :method => :delete %>
						<% end %>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>